#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ias
Version  : 6.0.1
Release  : 80
URL      : https://github.com/intel/ias/archive/6.0.1.tar.gz
Source0  : https://github.com/intel/ias/archive/6.0.1.tar.gz
Source1  : ias-setup.service
Source2  : ias-test-hmi.path
Source3  : ias-test-hmi.service
Source4  : ias.service
Summary  : Weston Compositor
Group    : Development/Tools
License  : CC-BY-SA-3.0 MIT
Requires: ias-autostart = %{version}-%{release}
Requires: ias-bin = %{version}-%{release}
Requires: ias-data = %{version}-%{release}
Requires: ias-lib = %{version}-%{release}
Requires: ias-libexec = %{version}-%{release}
Requires: ias-license = %{version}-%{release}
Requires: ias-services = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-allocators-1.0)
BuildRequires : pkgconfig(gstreamer-app-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libevdev)
BuildRequires : pkgconfig(libinput)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(mtdev)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-composite)
BuildRequires : pkgconfig(xcb-shape)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : sed
Patch1: 0001-add-example-ias-setup-script.patch
Patch2: 0001-truncate-instead-of-append-log-file.patch

%description
Weston compositor

%package autostart
Summary: autostart components for the ias package.
Group: Default

%description autostart
autostart components for the ias package.


%package bin
Summary: bin components for the ias package.
Group: Binaries
Requires: ias-data = %{version}-%{release}
Requires: ias-libexec = %{version}-%{release}
Requires: ias-license = %{version}-%{release}
Requires: ias-services = %{version}-%{release}

%description bin
bin components for the ias package.


%package data
Summary: data components for the ias package.
Group: Data

%description data
data components for the ias package.


%package dev
Summary: dev components for the ias package.
Group: Development
Requires: ias-lib = %{version}-%{release}
Requires: ias-bin = %{version}-%{release}
Requires: ias-data = %{version}-%{release}
Provides: ias-devel = %{version}-%{release}
Requires: ias = %{version}-%{release}

%description dev
dev components for the ias package.


%package lib
Summary: lib components for the ias package.
Group: Libraries
Requires: ias-data = %{version}-%{release}
Requires: ias-libexec = %{version}-%{release}
Requires: ias-license = %{version}-%{release}

%description lib
lib components for the ias package.


%package libexec
Summary: libexec components for the ias package.
Group: Default
Requires: ias-license = %{version}-%{release}

%description libexec
libexec components for the ias package.


%package license
Summary: license components for the ias package.
Group: Default

%description license
license components for the ias package.


%package services
Summary: services components for the ias package.
Group: Systemd services

%description services
services components for the ias package.


%prep
%setup -q -n ias-6.0.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1567009316
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain -Dsimple-dmabuf-drm=intel \
-Dbackend-rdp=false \
-Dcolor-management-colord=false \
-Denable-hyper-dmabuf=true  builddir
ninja -v -C builddir

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
:

%install
mkdir -p %{buildroot}/usr/share/package-licenses/ias
cp COPYING %{buildroot}/usr/share/package-licenses/ias/COPYING
cp data/COPYING %{buildroot}/usr/share/package-licenses/ias/data_COPYING
DESTDIR=%{buildroot} ninja -C builddir install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/ias-setup.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/ias-test-hmi.path
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/systemd/system/ias-test-hmi.service
install -m 0644 %{SOURCE4} %{buildroot}/usr/lib/systemd/system/ias.service
## install_append content
mkdir -p %{buildroot}/usr/share/xdg/weston/
install -m 0644 weston.ini.in %{buildroot}/usr/share/xdg/weston/weston.ini
install -m 0644 ias.conf.example %{buildroot}/usr/share/xdg/weston/ias.conf
mkdir -p %{buildroot}/usr/lib/systemd/system/ias.service.wants
mkdir -p %{buildroot}/usr/lib/systemd/system/basic.target.wants
ln -s ../ias-test-hmi.path %{buildroot}/usr/lib/systemd/system/ias.service.wants/ias-test-hmi.path
ln -s ../ias-setup.service %{buildroot}/usr/lib/systemd/system/basic.target.wants/ias-setup.service
install -m 0755 ias-setup %{buildroot}/usr/bin/ias-setup
mv %{buildroot}/usr/lib64/pkgconfig/weston.pc %{buildroot}/usr/lib64/pkgconfig/ias.pc
mv %{buildroot}/usr/include/weston %{buildroot}/usr/include/ias
rm %{buildroot}/usr/libexec/weston*
mv %{buildroot}/usr/bin/weston-screenshooter %{buildroot}/usr/bin/ias-screenshooter
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/basic.target.wants/ias-setup.service

%files bin
%defattr(-,root,root,-)
/usr/bin/ias-screenshooter
/usr/bin/ias-setup
/usr/bin/ias-weston
/usr/bin/ias-weston-launch

%files data
%defattr(-,root,root,-)
/usr/share/ias/background.png
/usr/share/ias/border.png
/usr/share/ias/examples/eglinfo
/usr/share/ias/examples/extension-test-client
/usr/share/ias/examples/ias-metrics
/usr/share/ias/examples/inputctrl
/usr/share/ias/examples/layoutctrl
/usr/share/ias/examples/mediaplayer
/usr/share/ias/examples/remote-display
/usr/share/ias/examples/remote-display-show
/usr/share/ias/examples/surfctrl
/usr/share/ias/examples/vmdisplay-input
/usr/share/ias/examples/vmdisplay-server
/usr/share/ias/examples/vmdisplay-wayland
/usr/share/ias/examples/wcap-decode
/usr/share/ias/examples/weston-calibrator
/usr/share/ias/examples/weston-clickdot
/usr/share/ias/examples/weston-cliptest
/usr/share/ias/examples/weston-confine
/usr/share/ias/examples/weston-debug
/usr/share/ias/examples/weston-dnd
/usr/share/ias/examples/weston-editor
/usr/share/ias/examples/weston-es2gears
/usr/share/ias/examples/weston-eventdemo
/usr/share/ias/examples/weston-flower
/usr/share/ias/examples/weston-fullscreen
/usr/share/ias/examples/weston-image
/usr/share/ias/examples/weston-info
/usr/share/ias/examples/weston-multi-resource
/usr/share/ias/examples/weston-presentation-shm
/usr/share/ias/examples/weston-resizor
/usr/share/ias/examples/weston-scaler
/usr/share/ias/examples/weston-simple-clock
/usr/share/ias/examples/weston-simple-damage
/usr/share/ias/examples/weston-simple-dmabuf-drm
/usr/share/ias/examples/weston-simple-dmabuf-egl
/usr/share/ias/examples/weston-simple-dmabuf-v4l
/usr/share/ias/examples/weston-simple-egl
/usr/share/ias/examples/weston-simple-egl-ms
/usr/share/ias/examples/weston-simple-shm
/usr/share/ias/examples/weston-simple-touch
/usr/share/ias/examples/weston-smoke
/usr/share/ias/examples/weston-stacking
/usr/share/ias/examples/weston-subsurfaces
/usr/share/ias/examples/weston-terminal
/usr/share/ias/examples/weston-touch-calibrator
/usr/share/ias/examples/weston-transformed
/usr/share/ias/examples/wrandr
/usr/share/ias/fullscreen.png
/usr/share/ias/home.png
/usr/share/ias/icon_editor.png
/usr/share/ias/icon_flower.png
/usr/share/ias/icon_ivi_clickdot.png
/usr/share/ias/icon_ivi_flower.png
/usr/share/ias/icon_ivi_simple-egl.png
/usr/share/ias/icon_ivi_simple-shm.png
/usr/share/ias/icon_ivi_smoke.png
/usr/share/ias/icon_terminal.png
/usr/share/ias/icon_window.png
/usr/share/ias/intel.png
/usr/share/ias/panel.png
/usr/share/ias/pattern.png
/usr/share/ias/protocols/weston-debug.xml
/usr/share/ias/random.png
/usr/share/ias/sidebyside.png
/usr/share/ias/sign_close.png
/usr/share/ias/sign_maximize.png
/usr/share/ias/sign_minimize.png
/usr/share/ias/terminal.png
/usr/share/ias/tiling.png
/usr/share/ias/wayland.png
/usr/share/ias/wayland.svg
/usr/share/pkgconfig/libias-6-protocols.pc
/usr/share/wayland-sessions/ias-weston.desktop
/usr/share/xdg/weston/ias.conf
/usr/share/xdg/weston/weston.ini

%files dev
%defattr(-,root,root,-)
/usr/include/ias/ivi-layout-export.h
/usr/include/ias/weston.h
/usr/include/libias-6/compositor-drm.h
/usr/include/libias-6/compositor-fbdev.h
/usr/include/libias-6/compositor-headless.h
/usr/include/libias-6/compositor-ias.h
/usr/include/libias-6/compositor-wayland.h
/usr/include/libias-6/compositor-x11.h
/usr/include/libias-6/compositor.h
/usr/include/libias-6/config-parser.h
/usr/include/libias-6/ias-common.h
/usr/include/libias-6/ias-plugin-framework-definitions.h
/usr/include/libias-6/ias-spug.h
/usr/include/libias-6/libweston-desktop.h
/usr/include/libias-6/matrix.h
/usr/include/libias-6/platform.h
/usr/include/libias-6/plugin-registry.h
/usr/include/libias-6/timeline-object.h
/usr/include/libias-6/version.h
/usr/include/libias-6/weston-egl-ext.h
/usr/include/libias-6/windowed-output-api.h
/usr/include/libias-6/xwayland-api.h
/usr/include/libias-6/zalloc.h
/usr/lib64/libias-6.so
/usr/lib64/libias-desktop-6.so
/usr/lib64/pkgconfig/ias.pc
/usr/lib64/pkgconfig/libias-6.pc
/usr/lib64/pkgconfig/libias-desktop-6.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/ias/cms-static.so
/usr/lib64/ias/cpp_example.so
/usr/lib64/ias/desktop-shell.so
/usr/lib64/ias/extension-sample.so
/usr/lib64/ias/fullscreen-shell.so
/usr/lib64/ias/gamma_example.so
/usr/lib64/ias/grid-layout.so
/usr/lib64/ias/hmi-controller.so
/usr/lib64/ias/ias-shell.so
/usr/lib64/ias/ias_plugin_framework.so
/usr/lib64/ias/input.so
/usr/lib64/ias/ivi-shell.so
/usr/lib64/ias/ivi_plugin_framework.so
/usr/lib64/ias/libias_hmi.so
/usr/lib64/ias/libwl_base.so
/usr/lib64/ias/libwl_disp.so
/usr/lib64/ias/screen-share.so
/usr/lib64/ias/sprite_example.so
/usr/lib64/ias/systemd-notify.so
/usr/lib64/ias/thumbnail.so
/usr/lib64/ias/transport_plugin_avb.so
/usr/lib64/ias/transport_plugin_file.so
/usr/lib64/ias/transport_plugin_tcp.so
/usr/lib64/ias/transport_plugin_udp.so
/usr/lib64/libias-6.so.0
/usr/lib64/libias-6.so.0.0.1
/usr/lib64/libias-6/drm-backend.so
/usr/lib64/libias-6/fbdev-backend.so
/usr/lib64/libias-6/gl-renderer.so
/usr/lib64/libias-6/headless-backend.so
/usr/lib64/libias-6/ias-backend.so
/usr/lib64/libias-6/remoting-plugin.so
/usr/lib64/libias-6/wayland-backend.so
/usr/lib64/libias-6/x11-backend.so
/usr/lib64/libias-6/xwayland.so
/usr/lib64/libias-desktop-6.so.0
/usr/lib64/libias-desktop-6.so.0.0.1

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ias-test-hmi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ias/COPYING
/usr/share/package-licenses/ias/data_COPYING

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/basic.target.wants/ias-setup.service
/usr/lib/systemd/system/ias-setup.service
/usr/lib/systemd/system/ias-test-hmi.path
/usr/lib/systemd/system/ias-test-hmi.service
/usr/lib/systemd/system/ias.service
/usr/lib/systemd/system/ias.service.wants/ias-test-hmi.path
