#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ias
Version  : 4.0.2.dev.plane.blend
Release  : 14
URL      : https://github.com/intel/ias/archive/4.0.2_dev_plane_blend.tar.gz
Source0  : https://github.com/intel/ias/archive/4.0.2_dev_plane_blend.tar.gz
Source1  : ias@.service
Summary  : Weston Compositor
Group    : Development/Tools
License  : CC-BY-SA-3.0 MIT
Requires: ias-data
BuildRequires : Linux-PAM-dev
BuildRequires : doxygen
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libinput)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(mtdev)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-composite)
BuildRequires : pkgconfig(xcb-shape)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : sed

%description
Weston compositor

%package data
Summary: data components for the ias package.
Group: Data

%description data
data components for the ias package.


%prep
%setup -q -n ias-4.0.2_dev_plane_blend

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536094015
%autogen --disable-static --disable-setuid-install \
--enable-ias-shell \
--disable-xkbcommon \
--enable-simple-clients \
--enable-clients \
--disable-wayland-compositor \
--disable-libunwind \
--disable-xwayland \
--disable-xwayland-test \
--disable-x11-compositor \
--disable-rpi-compositor \
--enable-ivi-plugin-manager \
--enable-layer-manager-control \
--disable-tracing \
--enable-shadergen \
--enable-demo-clients-install
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
:

%install
export SOURCE_DATE_EPOCH=1536094015
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ias
cp COPYING %{buildroot}/usr/share/doc/ias/COPYING
cp data/COPYING %{buildroot}/usr/share/doc/ias/data_COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/ias@.service
## install_append content
mkdir -p %{buildroot}/opt/ias
mv %{buildroot}/usr %{buildroot}/opt/ias/
mkdir -p %{buildroot}/usr/share/xdg/weston/
install -m 0644 weston.ini.in %{buildroot}/usr/share/xdg/weston/weston.ini
install -m 0644 ias.conf.example %{buildroot}/usr/share/xdg/weston/ias.conf
## install_append end

%files
%defattr(-,root,root,-)
/opt/ias/usr/bin/extension_test_client
/opt/ias/usr/bin/inputctrl
/opt/ias/usr/bin/layoutctrl
/opt/ias/usr/bin/surfctrl
/opt/ias/usr/bin/traceinfo
/opt/ias/usr/bin/wcap-decode
/opt/ias/usr/bin/weston
/opt/ias/usr/bin/weston-calibrator
/opt/ias/usr/bin/weston-clickdot
/opt/ias/usr/bin/weston-cliptest
/opt/ias/usr/bin/weston-confine
/opt/ias/usr/bin/weston-dnd
/opt/ias/usr/bin/weston-editor
/opt/ias/usr/bin/weston-es2gears
/opt/ias/usr/bin/weston-eventdemo
/opt/ias/usr/bin/weston-flower
/opt/ias/usr/bin/weston-fullscreen
/opt/ias/usr/bin/weston-image
/opt/ias/usr/bin/weston-info
/opt/ias/usr/bin/weston-launch
/opt/ias/usr/bin/weston-multi-resource
/opt/ias/usr/bin/weston-presentation-shm
/opt/ias/usr/bin/weston-resizor
/opt/ias/usr/bin/weston-scaler
/opt/ias/usr/bin/weston-simple-clock
/opt/ias/usr/bin/weston-simple-damage
/opt/ias/usr/bin/weston-simple-dmabuf-drm
/opt/ias/usr/bin/weston-simple-dmabuf-v4l
/opt/ias/usr/bin/weston-simple-egl
/opt/ias/usr/bin/weston-simple-shm
/opt/ias/usr/bin/weston-simple-touch
/opt/ias/usr/bin/weston-smoke
/opt/ias/usr/bin/weston-stacking
/opt/ias/usr/bin/weston-subsurfaces
/opt/ias/usr/bin/weston-terminal
/opt/ias/usr/bin/weston-transformed
/opt/ias/usr/bin/wrandr
/opt/ias/usr/include/ias-shell-client-protocol.h
/opt/ias/usr/include/libweston-4/compositor-drm.h
/opt/ias/usr/include/libweston-4/compositor-fbdev.h
/opt/ias/usr/include/libweston-4/compositor-headless.h
/opt/ias/usr/include/libweston-4/compositor-ias.h
/opt/ias/usr/include/libweston-4/compositor-rdp.h
/opt/ias/usr/include/libweston-4/compositor-wayland.h
/opt/ias/usr/include/libweston-4/compositor-x11.h
/opt/ias/usr/include/libweston-4/compositor.h
/opt/ias/usr/include/libweston-4/config-parser.h
/opt/ias/usr/include/libweston-4/ias-common.h
/opt/ias/usr/include/libweston-4/ias-plugin-framework-definitions.h
/opt/ias/usr/include/libweston-4/ias-spug.h
/opt/ias/usr/include/libweston-4/libweston-desktop.h
/opt/ias/usr/include/libweston-4/matrix.h
/opt/ias/usr/include/libweston-4/plugin-registry.h
/opt/ias/usr/include/libweston-4/timeline-object.h
/opt/ias/usr/include/libweston-4/version.h
/opt/ias/usr/include/libweston-4/weston-egl-ext.h
/opt/ias/usr/include/libweston-4/windowed-output-api.h
/opt/ias/usr/include/libweston-4/zalloc.h
/opt/ias/usr/include/weston/ivi-layout-export.h
/opt/ias/usr/include/weston/weston.h
/opt/ias/usr/lib/systemd/system/ias@.service
/opt/ias/usr/lib64/ias/cpp_example.so
/opt/ias/usr/lib64/ias/cpp_example.so.0
/opt/ias/usr/lib64/ias/cpp_example.so.0.0.0
/opt/ias/usr/lib64/ias/extension_sample.so
/opt/ias/usr/lib64/ias/extension_sample.so.0
/opt/ias/usr/lib64/ias/extension_sample.so.0.0.0
/opt/ias/usr/lib64/ias/grid_layout.so
/opt/ias/usr/lib64/ias/grid_layout.so.0
/opt/ias/usr/lib64/ias/grid_layout.so.0.0.0
/opt/ias/usr/lib64/ias/ias-shell-protocol.so
/opt/ias/usr/lib64/ias/input.so
/opt/ias/usr/lib64/ias/input.so.0
/opt/ias/usr/lib64/ias/input.so.0.0.0
/opt/ias/usr/lib64/ias/sprite_example.so
/opt/ias/usr/lib64/ias/sprite_example.so.0
/opt/ias/usr/lib64/ias/sprite_example.so.0.0.0
/opt/ias/usr/lib64/ias/surface_gbc_control.so
/opt/ias/usr/lib64/ias/surface_gbc_control.so.0
/opt/ias/usr/lib64/ias/surface_gbc_control.so.0.0.0
/opt/ias/usr/lib64/ias/thumbnail_layout.so
/opt/ias/usr/lib64/ias/thumbnail_layout.so.0
/opt/ias/usr/lib64/ias/thumbnail_layout.so.0.0.0
/opt/ias/usr/lib64/libweston-4.so
/opt/ias/usr/lib64/libweston-4.so.0
/opt/ias/usr/lib64/libweston-4.so.0.0.0
/opt/ias/usr/lib64/libweston-4/drm-backend.so
/opt/ias/usr/lib64/libweston-4/fbdev-backend.so
/opt/ias/usr/lib64/libweston-4/gl-renderer.so
/opt/ias/usr/lib64/libweston-4/headless-backend.so
/opt/ias/usr/lib64/libweston-4/ias-backend.so
/opt/ias/usr/lib64/libweston-desktop-4.so
/opt/ias/usr/lib64/libweston-desktop-4.so.0
/opt/ias/usr/lib64/libweston-desktop-4.so.0.0.0
/opt/ias/usr/lib64/pkgconfig/libweston-4.pc
/opt/ias/usr/lib64/pkgconfig/libweston-desktop-4.pc
/opt/ias/usr/lib64/pkgconfig/weston.pc
/opt/ias/usr/lib64/weston/cms-static.so
/opt/ias/usr/lib64/weston/desktop-shell.so
/opt/ias/usr/lib64/weston/fullscreen-shell.so
/opt/ias/usr/lib64/weston/hmi-controller.so
/opt/ias/usr/lib64/weston/ias-shell.so
/opt/ias/usr/lib64/weston/ias_plugin_framework.so
/opt/ias/usr/lib64/weston/ivi-shell.so
/opt/ias/usr/lib64/weston/ivi_plugin_framework.so
/opt/ias/usr/libexec/ias-test-hmi
/opt/ias/usr/libexec/weston-desktop-shell
/opt/ias/usr/libexec/weston-ivi-shell-user-interface
/opt/ias/usr/libexec/weston-keyboard
/opt/ias/usr/libexec/weston-screenshooter
/opt/ias/usr/libexec/weston-simple-im
/opt/ias/usr/share/doc/ias/COPYING
/opt/ias/usr/share/doc/ias/compositor.h
/opt/ias/usr/share/doc/ias/data_COPYING
/opt/ias/usr/share/doc/ias/grid_layout.c
/opt/ias/usr/share/doc/ias/ias-backend.xml
/opt/ias/usr/share/doc/ias/ias-layout-manager.xml
/opt/ias/usr/share/doc/ias/ias-plugin-framework.h
/opt/ias/usr/share/doc/ias/ias-shell.xml
/opt/ias/usr/share/doc/ias/ivi-application.xml
/opt/ias/usr/share/doc/ias/ivi-controller.xml
/opt/ias/usr/share/doc/ias/ivi-hmi-controller.xml
/opt/ias/usr/share/doc/ias/ivi-input.xml
/opt/ias/usr/share/doc/ias/layoutctrl.c
/opt/ias/usr/share/doc/ias/plugin_samples/cpp_example/grid_layout.cc
/opt/ias/usr/share/doc/ias/plugin_samples/extension_sample/extension_sample.c
/opt/ias/usr/share/doc/ias/plugin_samples/extension_sample/extension_test_client.c
/opt/ias/usr/share/doc/ias/plugin_samples/extension_sample/new-extension.xml
/opt/ias/usr/share/doc/ias/plugin_samples/gamma_example/surface_gbc_control.c
/opt/ias/usr/share/doc/ias/plugin_samples/input/input.c
/opt/ias/usr/share/doc/ias/plugin_samples/sprite_example/sprite_example.c
/opt/ias/usr/share/doc/ias/surfctrl.c
/opt/ias/usr/share/man/man1/weston.1
/opt/ias/usr/share/man/man5/weston.ini.5
/opt/ias/usr/share/man/man7/weston-drm.7
/opt/ias/usr/share/wayland-sessions/weston.desktop
/opt/ias/usr/share/weston/background.png
/opt/ias/usr/share/weston/border.png
/opt/ias/usr/share/weston/fullscreen.png
/opt/ias/usr/share/weston/home.png
/opt/ias/usr/share/weston/icon_editor.png
/opt/ias/usr/share/weston/icon_flower.png
/opt/ias/usr/share/weston/icon_ivi_clickdot.png
/opt/ias/usr/share/weston/icon_ivi_flower.png
/opt/ias/usr/share/weston/icon_ivi_simple-egl.png
/opt/ias/usr/share/weston/icon_ivi_simple-shm.png
/opt/ias/usr/share/weston/icon_ivi_smoke.png
/opt/ias/usr/share/weston/icon_terminal.png
/opt/ias/usr/share/weston/icon_window.png
/opt/ias/usr/share/weston/intel.png
/opt/ias/usr/share/weston/panel.png
/opt/ias/usr/share/weston/pattern.png
/opt/ias/usr/share/weston/random.png
/opt/ias/usr/share/weston/sidebyside.png
/opt/ias/usr/share/weston/sign_close.png
/opt/ias/usr/share/weston/sign_maximize.png
/opt/ias/usr/share/weston/sign_minimize.png
/opt/ias/usr/share/weston/terminal.png
/opt/ias/usr/share/weston/tiling.png
/opt/ias/usr/share/weston/wayland.png
/opt/ias/usr/share/weston/wayland.svg

%files data
%defattr(-,root,root,-)
/usr/share/xdg/weston/ias.conf
/usr/share/xdg/weston/weston.ini
